#
# GitLeaks Repo Specific Configuration
#
# This allowlist is used to help Red Hat ignore false positives during its code scans.
#

[allowlist]
  paths = [
    '''infra/applications/vault/input/charts/vault/templates/vault-certs/secrets.yaml''',
  ]
