---
# Source: ai-agent/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-config
immutable: false
data:
  CLIENT_TIMEOUT: "600.0"
  LLAMA_STACK_URL: "http://llamastack-with-config-service.llama-stack.svc.cluster.local:8321"
  MAX_INFER_ITERATIONS: "50"
  MAX_TOKENS: "5000"
  MODEL_ID: "llama-4-scout-17b-16e-w4a16"
  TEMPERATURE: "0.0"
