---
# Source: ai-agent/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ai-agent
  labels:
    app: ai-agent
    app.kubernetes.io/component: ai-agent
    app.kubernetes.io/instance: ai-agent
    app.kubernetes.io/name: ai-agent
    app.kubernetes.io/managed-by: Helm
  annotations:
    app.openshift.io/vcs-ref: "main"
    app.openshift.io/vcs-uri: "https://github.com/carlmes/etx-agentic-ai.git"
    openshift.io/generated-by: OpenShiftWebConsole
    meta.helm.sh/release-name: ai-agent
    meta.helm.sh/release-namespace: demo-application2
spec:
  ports:
  - name: 8000-tcp
    protocol: TCP
    port: 8000
    targetPort: 8000
  internalTrafficPolicy: Cluster
  type: ClusterIP
  sessionAffinity: None
  selector:
    app: ai-agent
    deployment: ai-agent
